### ISSUE TITLE
Support calendar events with a duration

### ISSUE THREAD

**Issue by thomaskoren** [isisaddons/isis-wicket-fullcalendar2#1]
The current implementation only supports instants (i.e. a single point in time). This is great for events like due dates of todo items. It should also provide an interface to visualize timespans (like for appointments). 
e.g.
via start (datetime) + end (datetime)
or start (datetime) + duration

**Comment by danhaywood** [comment]
moved to https://github.com/incodehq/incode-platform/issues/34
